# A list of blacklisted words :D
words = [
    'poop',
    'shit',
    'fuck',
    'nigger',
    'nigga',
    'cunt',
    'hoe',
    'bitch',
    'idiot',
    'asshole',
    "boob",
    "jerk",
    "slut",
    "piss",
    "prick",
    "whore",
    "twat",
    "cock",
    "ass"
]
